name: Release app

on:
  workflow_dispatch:
    inputs:
      releaseTag:
        description: 'Tag name for the release'
        required: true
        default: 'v1.0.0'

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        include:
          - name: linux
            runner: ubuntu-latest
            targets: "tar.gz AppImage deb"
            acrh: "--x64 --arm64 --armv7l"
          - name: win
            runner: windows-latest
            targets: "NSIS zip"
            acrh: "--x64 --ia32 --arm64"
          - name: mac
            runner: macos-latest
            targets: "dmg"
            acrh: "--x64 --arm64"

    name: ${{ matrix.name }}
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Github checkout
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2 # Install pnpm using packageManager key in package.json
        with:
          version: latest

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install Node dependencies
        run: pnpm install --frozen-lockfile

      - name: Install electron-builder globally
        run: pnpm add electron-builder -g

      - name: Build GoofCord
        run: pnpm run build

      - name: Package GoofCord
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: electron-builder ${{ matrix.arch }} --${{ matrix.name }} ${{ matrix.targets }} --publish=always