name: Release app

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        include:
          - name: Linux
            runner: ubuntu-20.04
            arch: x64,arm64,armv7l
          - name: Windows
            runner: windows-latest
            arch: x64,arm64,ia32
          - name: macOS
            runner: macos-latest
            arch: x64,arm64

    name: ${{ matrix.name }} (${{ matrix.arch }})
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Github checkout
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2 # Install pnpm using packageManager key in package.json
        with:
          version: latest

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install Node dependencies
        run: pnpm install --frozen-lockfile

      - name: Install electron-forge globally
        run: pnpm add electron-forge -g

      - name: Publish app
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pnpm run publish -- --arch=${{ matrix.arch }}